### ISSUE TITLE
runtimeClasspath is resolved unsafely when using parallel build

### ISSUE THREAD

**Issue by TWiStErRob** [gretty-gradle-plugin/gretty#146] opened 2020-03-27 01:15 UTC
#126/#80 is not solved by #129 fully, it still reproduces in parallel builds.

Really simple project setup with two modules, on depend on the other and `org.gradle.parallel=true`.
https://github.com/TWiStErRob/repros/tree/master/gretty/runtimeClasspath_gradle6_warning

## Expected
no message

## Actual
```text
> Task :served:appRun
The configuration :lib:runtimeClasspath was resolved without accessing the project in a safe manner.
This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project. 
See https://docs.gradle.org/5.6.4/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details.
This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
```

## Versions
```groovy
classpath "org.gretty:gretty:3.0.1"
```
```text
p:\projects\bugs\gretty\gretty_runtimeClasspath_gradle6>gradlew --version
------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Windows 10 10.0 amd64
```

**Comment by f4lco** [comment] 2021-03-25 08:37
Thanks for the reproduction. I was using:

```
gw -Dorg.gradle.parallel=true --warning-mode all --stacktrace :served:appRun
```

Which yields the following stacktrace:

<details>
<summary>

```
> Task :served:appRun
The configuration :lib:runtimeClasspath was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.6.4/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:566)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2300(DefaultConfiguration.java:139)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1241)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1230)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:75)
        at org.akhikhl.gretty.ProjectUtils.addProjectClassPathWithDependencies(ProjectUtils.groovy:97)
```

</summary>

```
> Task :served:appRun
The configuration :lib:runtimeClasspath was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.6.4/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:566)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2300(DefaultConfiguration.java:139)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1241)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1230)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:75)
        at org.akhikhl.gretty.ProjectUtils.addProjectClassPathWithDependencies(ProjectUtils.groovy:97)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.akhikhl.gretty.ProjectUtils$_addProjectClassPathWithDependencies_closure7.doCall(ProjectUtils.groovy:99)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:427)
        at org.akhikhl.gretty.ProjectUtils.addProjectClassPathWithDependencies(ProjectUtils.groovy:98)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.akhikhl.gretty.ProjectUtils.addProjectClassPathWithOverlays(ProjectUtils.groovy:79)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.akhikhl.gretty.ProjectUtils.getClassPath(ProjectUtils.groovy:68)
        at org.akhikhl.gretty.ProjectUtils$getClassPath$9.call(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask$1$2.resolveWebAppClassPath(StartBaseTask.groovy:216)
        at org.akhikhl.gretty.WebAppClassPathResolver$resolveWebAppClassPath.call(Unknown Source)
        at org.akhikhl.gretty.LauncherBase.writeWebAppClassPath(LauncherBase.groovy:346)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.akhikhl.gretty.LauncherBase$_writeRunConfigJson_closure6$_closure7$_closure8.doCall(LauncherBase.groovy:319)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.json.JsonDelegate.cloneDelegateAndGetContent(JsonDelegate.java:91)
        at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:214)
        at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
        at groovy.json.DefaultJsonGenerator.writeIterator(DefaultJsonGenerator.java:402)
        at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:202)
        at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
        at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
        at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:200)
        at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
        at groovy.json.DefaultJsonGenerator.toJson(DefaultJsonGenerator.java:98)
        at groovy.json.JsonBuilder.toString(JsonBuilder.java:378)
        at groovy.json.JsonBuilder.toPrettyString(JsonBuilder.java:392)
        at groovy.json.JsonBuilder$toPrettyString$0.call(Unknown Source)
        at org.akhikhl.gretty.LauncherBase.launchThread(LauncherBase.groovy:228)
        at org.akhikhl.gretty.LauncherBase.launch(LauncherBase.groovy:143)
        at org.akhikhl.gretty.Launcher$launch.call(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:79)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)
````
</details>

and points to the following method in Gretty:

```groovy
private static void addProjectClassPathWithDependencies(Set<URL> urls, Project proj, String dependencyConfigName) {
  if(proj.sourceSets.main.output.files.any { new File(it, 'META-INF/web-fragment.xml').exists() })
    urls.add proj.jar.archivePath.toURI().toURL()
  else
    urls.addAll proj.sourceSets.main.output.files.collect { it.toURI().toURL() }
  def dependencyConfig = proj.configurations.findByName(dependencyConfigName)
  if(dependencyConfig) {
    def files = dependencyConfig.fileCollection { !(it instanceof ProjectDependency) }
    def grettyProvidedCompileConfig = proj.configurations.findByName('grettyProvidedCompile')
    if(grettyProvidedCompileConfig)
      files = files - grettyProvidedCompileConfig
    urls.addAll(files.collect { it.toURI().toURL() })  // **HERE**
    dependencyConfig.allDependencies.withType(ProjectDependency).each { dep ->
      addProjectClassPathWithDependencies(urls, dep.getDependencyProject(), dependencyConfigName)
    }
  }
}
```

@wolfs do you have any advice how to fix this deprecation warning? Any hint would be greatly appreciated.

**Comment by TWiStErRob** [comment] 2021-03-25 10:20
*Tip: you can link to a file if you select a specific commit and select a line
(which you can by pressing (z) on GitHub and clicking on the line number when the file is open.)*

https://github.com/gretty-gradle-plugin/gretty/blob/5f30b979d08cac0f9242fef83ce2ad58c7c7256e/libs/gretty/src/main/groovy/org/akhikhl/gretty/ProjectUtils.groovy#L97

I think the problem is calling `collect { }` which resolves the `FileCollection`. There's an `FileCollection.elements` property and a `Provider.map` which would delay the resolution. Which could work depending on what you do with the URLs.

**Comment by wolfs** [comment] 2021-03-25 10:21
I think the problem is that the configuration in `libs` is resolved by the task in `served`, so it is reaching out to the configuration on another project directly. Maybe declaring the configuration as an input may work. The right solution is probably to publish the configuration you use with some attributes in the `libs` project and then depend on the full libs project requesting the right attributes. This would leverage variant aware dependency management, like shown here: https://docs.gradle.org/current/userguide/cross_project_publications.html#sec:variant-aware-sharing

**Comment by f4lco** [comment] 2021-03-26 10:05
@TWiStErRob thank you very much, that's a useful tip indeed 😃 

@wolfs declaring it as input likely does not work. I tried in a quite literal sense:

```diff
diff --git a/libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy b/libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy
index 81f0b8d9..210c1283 100644
--- a/libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy
+++ b/libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy
@@ -16,6 +16,7 @@ import org.gradle.api.Task
 import org.gradle.api.internal.TaskInternal
 import org.gradle.api.plugins.ExtensionAware
 import org.gradle.api.tasks.Input
+import org.gradle.api.tasks.InputFiles
 import org.gradle.api.tasks.Internal
 import org.gradle.api.tasks.Optional
 import org.gradle.api.tasks.TaskAction
@@ -280,6 +281,11 @@ abstract class StartBaseTask extends DefaultTask {
     }
   }

+  @InputFiles
+  Iterable<File> getProjectInputClassPath() {
+    return project.project(":lib").configurations["runtimeClasspath"]
+  }
+
   final void jacoco(Closure configureClosure) {
     getJacoco()?.with configureClosure
   }
```

But Gradle showed the same warning.

> The right solution is probably to publish the configuration you use with some attributes in the libs project and then depend on the full libs project requesting the right attributes.

I understand that reaching out to other projects configurations at any time might be problematic. But do I really need to create new configurations in "libs", or participate in variant-aware dependency resolution?

Would you consider the following approach worth a try:
- assuming that I'm always free to access (and resolve) configurations of the current project, and
- assuming that the key to safe resolution is one step of indirection, meaning: do not reach into configurations of other projects directly, but reference them from a configuration of my own,
- I can programmatically create a configuration for the current project, which references configurations of other projects (maybe via a dependency on `project(path: ':lib', configuration: 'runtimeClasspath')`, and safely use the result of resolving that configuration to a set of files?

**Closed** 2021-03-30 09:34 UTC
