### ISSUE TITLE
appRun throws exception when adding resourceBase

### ISSUE THREAD

**Issue by johndevs** [gretty-gradle-plugin/gretty#116] opened 2019-03-16 16:15 UTC
When using the following build.gradle:

```
plugins {
    id 'org.gretty' version '2.3.1'
}

ext {
    jetty94Version = '9.4.15.v20190215'
}

gretty {
    servletContainer = 'jetty9.4'
    extraResourceBase new File(project.buildDir, 'some-dir')
}
```

The following exception is thrown:
```
18:11:24 WARN  Failed startup of context o.a.g.JettyWebAppContext@971e903{/vaadinFlowPluginTest,/vaadinFlowPluginTest,[file:///home/john/Public/vaadinFlowPluginTest/build/inplaceWebapp/, file:///home/john/Public/vaadinFlowPluginTest/build/webapp-gen/, file:///home/john/Public/vaadinFlowPluginTest/build/webapp-gen/],UNAVAILABLE}
groovy.lang.MissingMethodException: No signature of method: org.eclipse.jetty.util.resource.ResourceCollection.findResource() is applicable for argument types: (java.lang.String) values: [META-INF/jetty9.4-env.xml]
Possible solutions: getResource(java.lang.String), newResource(java.lang.String), newResource(java.io.File), newResource(java.net.URI), newResource(java.net.URL), newResource(java.nio.file.Path)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:71) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:48) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128) ~[groovy-2.4.15.jar:2.4.15]
        at org.akhikhl.gretty.JettyConfigurerImpl.findResourceURL(JettyConfigurerImpl.groovy:246) ~[gretty-runner-jetty94-2.3.1.jar:na]
        at org.akhikhl.gretty.JettyConfigurer$findResourceURL$9.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136) ~[groovy-2.4.15.jar:2.4.15]
        at org.akhikhl.gretty.JettyServerConfigurer.getContextConfigFile(JettyServerConfigurer.groovy:130) ~[gretty-runner-jetty-2.3.1.jar:na]
        at org.akhikhl.gretty.JettyServerConfigurer$getContextConfigFile$1.callCurrent(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177) ~[groovy-2.4.15.jar:2.4.15]
        at org.akhikhl.gretty.JettyServerConfigurer.configureWithBaseResource(JettyServerConfigurer.groovy:34) ~[gretty-runner-jetty-2.3.1.jar:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1092) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1099) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.Closure.call(Closure.java:418) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.Closure.call(Closure.java:434) ~[groovy-2.4.15.jar:2.4.15]
        at groovy.lang.Closure$call$0.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128) ~[groovy-2.4.15.jar:2.4.15]
        at org.akhikhl.gretty.WebInfConfigurationEx.unpack(WebInfConfigurationEx.groovy:49) ~[gretty-runner-jetty94-2.3.1.jar:na]
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:152) ~[jetty-webapp-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506) ~[jetty-webapp-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544) ~[jetty-webapp-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.akhikhl.gretty.JettyWebAppContext.doStart(JettyWebAppContext.groovy:44) ~[gretty-runner-jetty94-2.3.1.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:168) ~[jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.Server.start(Server.java:415) ~[jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) ~[jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.Server.doStart(Server.java:382) ~[jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.component.LifeCycle$start$0.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120) ~[groovy-2.4.15.jar:2.4.15]
        at org.akhikhl.gretty.JettyServerManager.startServer(JettyServerManager.groovy:48) ~[gretty-runner-jetty-2.3.1.jar:na]
        at org.akhikhl.gretty.ServerManager$startServer$0.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128) ~[groovy-2.4.15.jar:2.4.15]
        at org.akhikhl.gretty.Runner.run(Runner.groovy:121) ~[gretty-runner-2.3.1.jar:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-2.4.15.jar:2.4.15]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120) ~[groovy-2.4.15.jar:2.4.15]
        at org.akhikhl.gretty.Runner.main(Runner.groovy:48) ~[gretty-runner-2.3.1.jar:na]
```

**Comment by johndevs** [comment] 2019-03-16 16:26
Looks like the ``findResource`` -method (which previously was protected) has been removed from ``ResourceCollection``. 

https://www.eclipse.org/jetty/javadoc/9.4.15.v20190215/org/eclipse/jetty/util/resource/ResourceCollection.html

**Comment by gregorko** [comment] 2019-03-26 14:08
Here is the corresponding commit that removes the ```ResourceCollection.findResource(String)``` method.
https://github.com/eclipse/jetty.project/commit/8969c9a18cd86e0eff3dd5651fe6ddb165b2ad58#diff-ca8a7c586007366cbd605eeecbd70d1b

The method ```ResourceCollection.addPath(String)``` looks very similar and might work as an alternative.

**Comment by boris-petrov** [comment] 2024-08-16 11:14
I believe this is a duplicate of #120 and has been fixed for... a few years now. :)

**Closed by boris-petrov** 2024-08-16 11:14 UTC
