### ISSUE TITLE
implementation dependency not included cause ClassNotFoundException

### ISSUE THREAD

**Issue by riceyeh** [gretty-gradle-plugin/gretty#41] opened 2018-04-30 01:18 UTC
Hi,
  In recent versions of gradle, compile dependency is deprecated and replaced by implementation dependency. I find this is not considered by gretty and hence not have implementation dependencies included when doing appRun and cause ClassNotFoundException.

**Comment by javabrett** [comment] 2018-04-30 04:42
This looks like a duplicate of [#37 #12 akhikhl#377].  A fix was merged to master last week - would you be able to try that out using the master nightly build e.g. using https://raw.githubusercontent.com/gretty-gradle-plugin/gretty/master/pluginScripts/gretty-SNAPSHOT.plugin and report back.  If that build exhibits the problem could you post a minimal example?

**Comment by riceyeh** [comment] 2018-04-30 15:48
Have tried it and it works. Thanks.

**Closed** 2018-04-30 17:30 UTC
Labels: duplicate
