### ISSUE TITLE
Support All Dependencies Override In Project gradle.properties file

### ISSUE THREAD

**Issue by ankurpathak** [gretty-gradle-plugin/gretty#90] opened 2018-11-18 13:45 UTC
I have tried gretty 3.0.0-SNAPSHOT. But not supporting overide of following dependencies:
jetty7_version = 7.6.21.v20160908
jetty7_servlet_api_version = 2.5
jetty8_version = 8.1.22.v20160922
jetty8_servlet_api_version = 3.0.1
jetty9_version = 9.2.26.v20180806
jetty93_version = 9.3.24.v20180605
jetty94_version = 9.4.11.v20180605
jetty9_servlet_api_version = 3.1.0
tomcat85_version = 8.5.33
tomcat85_servlet_api_version = 3.1.0
tomcat9_version = 9.0.11
tomcat9_servlet_api_version = 4.0.0
asm_version = 7.0
groovy_version = 2.4.15
spock_version = 1.1-groovy-2.4
logback_version = 1.1.3
slf4j_version = 1.7.12
springBootVersion = 2.0.2.RELEASE
springLoadedVersion = 1.2.8.RELEASE
springVersion = 5.0.6.RELEASE

 by gradle.properties of my project:. When I list following dependecies in my project gradle.properties file by:
jetty94_version = 9.4.14.v20181114
tomcat85_version = 8.5.35
tomcat9_version = 9.0.13
Its downloading the version listed in plugin instead of version listed by me. I ahve read in this stackflow post that overiding dependencies version are supported:
https://stackoverflow.com/questions/37339515/how-to-select-specific-jetty-version-in-gretty-plugin
And in plugin documentation at this url:
http://akhikhl.github.io/gretty-doc/Overriding-servlet-container-versions.html
So please add support for this dependency overide as well. The only alternative we have if we don't have this feature is to build plugin from source code overiding dependencies ourself and use it from
local maven repository.

**Comment by javabrett** [comment] 2018-11-18 21:05
According to the link and the newer https://gretty-gradle-plugin.github.io/gretty-doc/Overriding-servlet-container-versions.html , the required property form is e.g.:

```
jetty94Version=9.4.11.v20180605
```

... paying close attention to format and case.

Can you try that again in your project, and if not working, please post a link to a test-project sources.

**Comment by ankurpathak** [comment] 2018-11-20 06:48
1. First of sorry, for using wrong properties in project gradle.properties because of similar sounding name
for plugin gradle.properties and project gradle.properties.
2. Here is a sample project on github url:
https://github.com/ankurpathak/gradle-web 
and please read the read me file for sure on github url:
https://github.com/ankurpathak/gradle-web/blob/master/README.md
3. From my oveservation its working for Jetty 9.4 by using adding follwing property in project gradle.properties:
jetty94Version = 9.4.14.v20181114
as per docs.
4. But as per docs their is no similar property for Tomcat 8.5 and Tomcat 9. But then also I tried addind follwing to project gradle.properties on similar lines of Tomcat 8 and Jetty 9.4:
tomcat9Version = 9.0.13
tomcat85Version = 8.5.35
It doesn't worked for tomcat 8.5 and Tomcat 9.0
5. So we should add following properties to plugin for Tomcat 8.5 and Tomcat 9.0:
tomcat9Version = 9.0.13
tomcat85Version = 8.5.35
allowing overide for Tomcat 8.5 and Tomcat 9.0 on similar lines of Tomcat 8 and Jetty 9.4.

**Comment by javabrett** [comment] 2018-11-20 09:55
I'm not able to reproduce this problem, running a test-project against a local Gretty `3.0.0-SNAPSHOT` build.

If I set `build.gradle`:

```
gretty {
  servletContainer = 'tomcat9'
  httpPort = 8080
}
```

... I get default/latest Tomcat 9.0.13 when I run `appRunWar`.  If I then add `gradle.properties`:

```
tomcat9Version=9.0.12
```

... and restart, I'm running Tomcat 9.0.12.

**Comment by javabrett** [comment] 2018-11-28 00:49
Closing as this works for me.  @ankurpathak please reopen if still an issue, providing further details.

**Closed by javabrett** 2018-11-28 00:49 UTC
